### ISSUE TITLE
IG Charter 2023: Update scope

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-charter-drafts#122]
- explain relationship to WoT CG and WoT JP CG
- reduce scope for items that are now covered by CG
- mention "gathering and documenting use cases and requirements"
- (discuss; debatable) list "testing" as an IG role (to allow for contributions from non-WG members) - really should be WG, IR is WG's responsibility
- maintaining online resources such as the website
- (discuss) draft proposed specifications - perhaps better in CG
- (discuss) "guideline" documents like the S&PG docs and a possible "implementation guideline/best practices" docs.

**Comment by mjkoster** [comment]
Discussion of scope summary
- remove "tutorials"
- MJK to go to the mailing list collect opinions and make PR after Friday

**Comment by mjkoster** [comment]
- add: entry point for new users and members who are not yet in the WG to join and contribute

**Comment by mjkoster** [comment]
MJK to do in time for review before 1/31/2024 meeting

**Comment by mjkoster** [comment]
Draft is updated
