### ISSUE TITLE
Clean up after separating details

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-charter-drafts#22]
after https://github.com/w3c/wot-charter-drafts/pull/21, clean up details.html so it renders properly, create a rendering link for it in the README, and fix the broken hyperlinks in the main draft.

**Comment by benfrancis** [comment]
See also: https://github.com/w3c/wot-charter-drafts/pull/21#issuecomment-1429730129

Nearly all of the content relating to profiles was removed in #21.
