### ISSUE TITLE
Expand CG collaboration

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-charter-drafts#36]
Current charter has the following item:

> For collaboration on community outreach of the WG reports to increase adoption and implementation, as well as collecting feedback from the global community. Meetings held in English.

We should change such that a stronger collaboration is apparent. My proposal

> For collaboration on community outreach of the WG reports to increase adoption and implementation, as well as collecting feedback from the global community via reports or joint events. Meetings held in English.

**Comment by mmccool** [comment]
Not sure we really need the "via" part, but if we do add it, we should do something similar for the WoT JP CG, which will also generate reports, do translations, etc.
