### ISSUE TITLE
Versioning of Specifications

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-charter-drafts#38]
- Do we want them at all?
- We already have them in some docs, e.g. Arch and TD
- Semantic versioning and backward compatibility; not recognized by W3C
- But if don't have version numbers, need to be strict about referring to publication dates
- Would be clearer if all version numbers are coordinated (e.g. "Discovery 2.0 should use TD 2.0") - is about "WoT 2.0"
- We can also skip version numbers if we want to synch versions, e.g. for Profiles can skip 1.1 (or even 1.0) and go straight to 2.0.
- Publication dates are just another kind of version number
- We probably will be discussing some breaking changes in this charter
- Keeping things simple for adopters/implementers should be a goal
- Versions with breaking changes acceptable IF they address a large number of small problems or major problems

**Comment by ashimura** [comment]
Please see also: https://www.w3.org/2005/05/tr-versions

**Comment by mmccool** [comment]
- Kaz: are already some policies in place, but does vary by WG (e.g. HTML does not, CSS does, calls them "Levels")
- Ege: to be clear with proposal, all documents should use versions, including new ones
- Seb: deliverables usually mention WoT, maybe we should attach a version to "WoT": e.g. "WoT 2.0 Discovery", "WoT 2.0 Profiles"
- Luca: Alternative would be to have one "hub" document, then that links to other specific versions that are in "WoT 2.0"; hub can also be an explainer

Proposal:
- Will use semantic versioning
- This charter's deliverables would ALL be 2.0
     - ...even if there was no previously published 1.0).
- Global versioning for all of WoT, kept in sync across all documents, including new ones.
     - Binding the version to "WoT" instead of to the doc name might be helpful.)
- Intermediate publications, e.g. updates to Scripting, can use publication date as a "minor" version (in effect, this is what we are doing already)

**Comment by mmccool** [comment]
Proposal: Use "WoT 2.0" approach.  Note we are talking about 2.0, not 1.2.   So specs would in general be named something like: "Web of Things 2.0 X" where X is Discovery, Thing Description, etc.  Note "WoT" also goes away.

**Comment by mmccool** [comment]
Discussion:
- Need to compare how other groups do this, and W3M needs to be consulted.
- Want to keep the semantic versioning approach, just make it consistent across documents
- Managing versioning at the system level is hard; what if TD needs breaking changes and Discovery does not?
- If use 2.0, need to clarify major differences.  Need to document why we need breaking changes...

**Comment by mmccool** [comment]
For the charter, we don't have to commit to this, so let's change the "deliverable" titles to higher level "descriptions" like
* Discovery Update
* Thing Description Update
* Profile Update
etc.

Maybe add a sentence saying the exact titles of these documents will be chosen after discussion within the WG.
