### ISSUE TITLE
Do we keep Privacy and Accessibility Groups?

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-charter-drafts#45]
not technically needed to mention, since wide review groups

**Comment by mmccool** [comment]
I made two PRs for two possible solutions to this issue, for us to discuss:
1. #49 - remove mention of other Privacy or A11y groups.
2. #50 - update description of A11y group to parallel privacy and emphasize "in addition to horizontal review".

We should merge at most one of the above.  I am in favor of merging #50 myself.

**Comment by egekorkan** [comment]
I am strongly in favour of not removing them and having better cooperation. There are a couple of features in the TD that needs this kind of collab. Also, onboarding topic will definitely involve some privacy concerns and getting their review after 2 years seems too long.

**Comment by mmccool** [comment]
Updated text, but we still want to discuss with APA and PING whether these are appropriate, and whether the text is the right text.

**Comment by mmccool** [comment]
I have sent emails to both PING and APA asking for their reviews and input.

**Comment by michael-n-cooper** [comment]
[Response to APA ping](https://lists.w3.org/Archives/Group/group-apa-chairs/2023Mar/0017.html) from @matatk anticipating comment soon.

**Comment by mmccool** [comment]
- Got feedback from APA that they are ok with current text
- Have not heard from PING
- Note that there are no specific work items for APA, however

**Comment by mmccool** [comment]
Propose: keep current text explicitly mentioning PING and API, then see what additional feedback we get during review.
