### ISSUE TITLE
Removing reference to WoT Current Practices

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-charter-drafts#47]
The current charter links to a document I have never seen before: https://w3c.github.io/wot/current-practices/wot-practices.html#plugfests

The link is actually in the background paragraph, right above the scope, so actually quite high up and visible.

Given that this document is severely outdated, I think we should not link it and ideally decide on what to do with it.

**Comment by egekorkan** [comment]
It even has the automatic date generated by respec...

**Comment by danielpeintner** [comment]
The _current_ data on the old **document** is definitively confusing!

Just briefly summarizing what was the reason behind the document. At that time (year 2017 and before) the spec documents were not as clear and ready as they are now. Hence we tried to give people best practices (and help w.r.t. changes between notes) to make progress in PlugFests. 

Anyhow, we should archive the document (or mark it clearly as out-dated).

**Comment by egekorkan** [comment]
This has been done already. Closing.

**Comment by danielpeintner** [comment]
Question: I wonder whether we should add a RED disclaimer at the top of https://w3c.github.io/wot/current-practices/wot-practices.html saying that this document is **NOT** up-to-date anymore. Otherwise people will be confused  since it is still showing a current date.

**Comment by mmccool** [comment]
The link has been taken out so this issue no longer impacts the charter but @danielpeintner reopened it to request adding a disclaimer to the referenced document.  @danielpeintner can you make a PR to add the appropriate disclaimer?

**Comment by danielpeintner** [comment]
Closing. Handle the issue in https://github.com/w3c/wot/issues/1079
