### ISSUE TITLE
TD: Add composed Things work items

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-charter-drafts#59]
There have many discussions in the past about how to represent entities like a room "thing" that is actually just affordances of other things that are sensors. I think that this goes in the TD spec but comments are welcome.

**Comment by mmccool** [comment]
Somewhat relates to some "digital twins" topics e.g. linked things.  But I agree, it can be covered in "Details".

**Comment by egekorkan** [comment]
We will move this discussion to TD repo and mark TD 2.0

**Comment by egekorkan** [comment]
Moved to TD spec at https://github.com/w3c/wot-thing-description/issues/1902, closing here.
