### ISSUE TITLE
Move IG Relationship from Mission Statement to Collaboration

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-charter-drafts#65]
Coming from the charter call on 27.02.2023

In the charter, we should make clear what kind of collaboration we have with other groups, including WoT IG. Below are the texts in question:

- This Working Group Charter covers those aspects that the [Web of Things Interest Group](http://www.w3.org/groups/ig/wot) [(charter here)](https://www.w3.org/2021/12/wot-ig-2021.html) believes are mature enough to progress to W3C Recommendations.
- As a continuation of the work in [the previous charter](https://www.w3.org/2022/07/wot-wg-2022.html), this working group is tasked with the standardization or extension of the building blocks identified by the use cases resulting from the work of [the Web of Things Interest Group](https://www.w3.org/groups/ig/wot) (IG) as being important to advance the Web of Things.

The first PR should move these to the coordination section and then another should provide a diagram that explains the relationships.

**Comment by mmccool** [comment]
I don't think we necessarily need a diagram but agree that the IG text doesn't really belong in the mission statement, which should be about the *WG* mission.  I agree with the plan to move it under "Collaboration" (consolidating as necessary).

Who's doing a PR?
